### ISSUE TITLE
The CJS file contains ESM code

### ISSUE THREAD

**Issue by eilvelia** [evi1Husky/PorterStemmer#1]
The `.cjs` file in the new `v1.1.1` version is incorrect because it includes the `export { ... }` ESM's statement, requiring it fails:

```
/.../porter-stemmer-js/src/PorterStemmer.cjs:252
export { PorterStemmer }
^^^^^^

SyntaxError: Unexpected token 'export'
```

edit: By the way, I cannot really reproduce large performance difference betweeen `1.1.0` and `1.1.1`

**Comment by evi1Husky** [comment]
fixed
